using FinanzasMCP.Application.Accounts.Handlers;
using FinanzasMCP.Application.Accounts.Commands;
using FinanzasMCP.Application.CryptoAccounts.Handlers;
using FinanzasMCP.Application.CryptoAccounts.Commands;
using FinanzasMCP.Application.CryptoAccounts.Queries;
using FinanzasMCP.Application.AccountingPeriods.Handlers;
using FinanzasMCP.Application.AccountingPeriods.Commands;
using FinanzasMCP.Application.AccountingPeriods.Queries;
using FinanzasMCP.Application.Budgets.Handlers;
using FinanzasMCP.Application.Budgets.Commands;
using FinanzasMCP.Application.Categories.Handlers;
using FinanzasMCP.Application.Categories.Commands;
using FinanzasMCP.Application.Crypto.Handlers;
using FinanzasMCP.Application.Crypto.Commands;
using FinanzasMCP.Application.Crypto.Queries;
using FinanzasMCP.Application.CreditCards.Handlers;
using FinanzasMCP.Application.CreditCards.Services;
using FinanzasMCP.Application.Debts.Handlers;
using FinanzasMCP.Application.Debts.Services;
using FinanzasMCP.Application.Debts.Commands;
using FinanzasMCP.Application.Debts.Queries;
using FinanzasMCP.Application.Goals.Handlers;
using FinanzasMCP.Application.RecurringRules.Handlers;
using FinanzasMCP.Application.RecurringRules.Commands;
using FinanzasMCP.Application.RecurringRules.Queries;
using FinanzasMCP.Application.Shopping;
using FinanzasMCP.Application.Tags.Handlers;
using FinanzasMCP.Application.Tags.Commands;
using FinanzasMCP.Application.Transactions.Handlers;
using FinanzasMCP.Application.Transactions.Commands;
using FinanzasMCP.Application.UserContext.Handlers;
using FinanzasMCP.Application.UserContext.Commands;
using FinanzasMCP.Application.UserContext.Queries;
using FinanzasMCP.Application.Reports.Handlers;
using FinanzasMCP.Application.Reports.Queries;
using FinanzasMCP.Application.Auth.Handlers;
using Microsoft.Extensions.DependencyInjection;

namespace FinanzasMCP.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddScoped<CreateAccountHandler>();
        services.AddScoped<GetAccountsHandler>();
        services.AddScoped<UpdateAccountHandler>();
        services.AddScoped<DeleteAccountHandler>();
        services.AddScoped<CreateCryptoAccountHandler>();
        services.AddScoped<GetCryptoAccountsHandler>();
        services.AddScoped<UpdateCryptoAccountHandler>();
        services.AddScoped<DeleteCryptoAccountHandler>();
        services.AddScoped<CreditCardTransactionService>();
        services.AddScoped<CreateCreditCardHandler>();
        services.AddScoped<GetCreditCardsHandler>();
        services.AddScoped<UpdateCreditCardHandler>();
        services.AddScoped<DeleteCreditCardHandler>();
        services.AddScoped<GetCreditCardStatementsHandler>();
        services.AddScoped<CloseCreditCardStatementHandler>();
        services.AddScoped<CreateCryptoLotHandler>();
        services.AddScoped<GetCryptoLotsHandler>();
        services.AddScoped<UpdateCryptoLotHandler>();
        services.AddScoped<DeleteCryptoLotHandler>();
        services.AddScoped<CreateAccountingPeriodHandler>();
        services.AddScoped<GetAccountingPeriodsHandler>();
        services.AddScoped<UpdateAccountingPeriodHandler>();
        services.AddScoped<DeleteAccountingPeriodHandler>();
        services.AddScoped<CreateCategoryHandler>();
        services.AddScoped<GetCategoriesHandler>();
        services.AddScoped<UpdateCategoryHandler>();
        services.AddScoped<DeleteCategoryHandler>();
        services.AddScoped<CreateTagHandler>();
        services.AddScoped<GetTagsHandler>();
        services.AddScoped<UpdateTagHandler>();
        services.AddScoped<DeleteTagHandler>();
        services.AddScoped<CreateTransactionHandler>();
        services.AddScoped<GetTransactionsHandler>();
        services.AddScoped<GetTransactionTotalsHandler>();
        services.AddScoped<UpdateTransactionHandler>();
        services.AddScoped<DeleteTransactionHandler>();
        services.AddScoped<CreateBudgetHandler>();
        services.AddScoped<GetBudgetsHandler>();
        services.AddScoped<GetBudgetUsageHistoryHandler>();
        services.AddScoped<UpdateBudgetHandler>();
        services.AddScoped<DeleteBudgetHandler>();
        services.AddScoped<CreateFinancialGoalHandler>();
        services.AddScoped<GetFinancialGoalsHandler>();
        services.AddScoped<UpdateFinancialGoalHandler>();
        services.AddScoped<DeleteFinancialGoalHandler>();
        services.AddScoped<CreateDebtHandler>();
        services.AddScoped<UpdateDebtHandler>();
        services.AddScoped<GetDebtInstallmentsHandler>();
        services.AddScoped<DebtInstallmentScheduleService>();
        services.AddScoped<DeleteDebtHandler>();
        services.AddScoped<GetDebtsHandler>();
        services.AddScoped<AddFinancialGoalContributionHandler>();
        services.AddScoped<UpdateFinancialGoalContributionHandler>();
        services.AddScoped<DeleteFinancialGoalContributionHandler>();
        services.AddScoped<GetFinancialGoalContributionsHandler>();
        services.AddScoped<RegisterDebtPaymentHandler>();
        services.AddScoped<UpdateDebtPaymentHandler>();
        services.AddScoped<DeleteDebtPaymentHandler>();
        services.AddScoped<GetDebtPaymentsHandler>();
        services.AddScoped<CreateRecurringRuleHandler>();
        services.AddScoped<GetRecurringRulesHandler>();
        services.AddScoped<UpdateRecurringRuleHandler>();
        services.AddScoped<DeleteRecurringRuleHandler>();
        services.AddScoped<UpsertUserContextEntryHandler>();
        services.AddScoped<GetUserContextHandler>();
        services.AddScoped<DeleteUserContextEntryHandler>();
        services.AddScoped<CreateUserApiKeyHandler>();
        services.AddScoped<GetUserApiKeysHandler>();
        services.AddScoped<RevokeUserApiKeyHandler>();
        services.AddScoped<DeleteUserApiKeyHandler>();
        services.AddScoped<GetFinanceOverviewHandler>();
        services.AddScoped<ShoppingService>();
        return services;
    }
}
