using FinanzasMCP.Application.Accounts.Handlers;
using FinanzasMCP.Application.Accounts.Commands;
using FinanzasMCP.Application.CryptoAccounts.Handlers;
using FinanzasMCP.Application.CryptoAccounts.Commands;
using FinanzasMCP.Application.CryptoAccounts.Queries;
using FinanzasMCP.Application.AccountingPeriods.Handlers;
using FinanzasMCP.Application.AccountingPeriods.Commands;
using FinanzasMCP.Application.AccountingPeriods.Queries;
using FinanzasMCP.Application.Budgets.Handlers;
using FinanzasMCP.Application.Budgets.Commands;
using FinanzasMCP.Application.Categories.Handlers;
using FinanzasMCP.Application.Categories.Commands;
using FinanzasMCP.Application.Crypto.Handlers;
using FinanzasMCP.Application.Crypto.Commands;
using FinanzasMCP.Application.Crypto.Queries;
using FinanzasMCP.Application.Debts.Handlers;
using FinanzasMCP.Application.Debts.Commands;
using FinanzasMCP.Application.Debts.Queries;
using FinanzasMCP.Application.PurchaseGoals.Handlers;
using FinanzasMCP.Application.PurchaseGoals.Commands;
using FinanzasMCP.Application.PurchaseGoals.Queries;
using FinanzasMCP.Application.RecurringRules.Handlers;
using FinanzasMCP.Application.RecurringRules.Commands;
using FinanzasMCP.Application.RecurringRules.Queries;
using FinanzasMCP.Application.SavingGoals.Handlers;
using FinanzasMCP.Application.SavingGoals.Commands;
using FinanzasMCP.Application.SavingGoals.Queries;
using FinanzasMCP.Application.Tags.Handlers;
using FinanzasMCP.Application.Tags.Commands;
using FinanzasMCP.Application.Transactions.Handlers;
using FinanzasMCP.Application.Transactions.Commands;
using FinanzasMCP.Application.UserContext.Handlers;
using FinanzasMCP.Application.UserContext.Commands;
using FinanzasMCP.Application.UserContext.Queries;
using FinanzasMCP.Application.Reports.Handlers;
using FinanzasMCP.Application.Reports.Queries;
using Microsoft.Extensions.DependencyInjection;

namespace FinanzasMCP.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddScoped<CreateAccountHandler>();
        services.AddScoped<GetAccountsHandler>();
        services.AddScoped<UpdateAccountHandler>();
        services.AddScoped<DeleteAccountHandler>();
        services.AddScoped<CreateCryptoAccountHandler>();
        services.AddScoped<GetCryptoAccountsHandler>();
        services.AddScoped<UpdateCryptoAccountHandler>();
        services.AddScoped<DeleteCryptoAccountHandler>();
        services.AddScoped<CreateCryptoLotHandler>();
        services.AddScoped<GetCryptoLotsHandler>();
        services.AddScoped<UpdateCryptoLotHandler>();
        services.AddScoped<DeleteCryptoLotHandler>();
        services.AddScoped<CreateAccountingPeriodHandler>();
        services.AddScoped<GetAccountingPeriodsHandler>();
        services.AddScoped<UpdateAccountingPeriodHandler>();
        services.AddScoped<DeleteAccountingPeriodHandler>();
        services.AddScoped<CreateCategoryHandler>();
        services.AddScoped<GetCategoriesHandler>();
        services.AddScoped<UpdateCategoryHandler>();
        services.AddScoped<DeleteCategoryHandler>();
        services.AddScoped<CreateTagHandler>();
        services.AddScoped<GetTagsHandler>();
        services.AddScoped<UpdateTagHandler>();
        services.AddScoped<DeleteTagHandler>();
        services.AddScoped<CreateTransactionHandler>();
        services.AddScoped<GetTransactionsHandler>();
        services.AddScoped<UpdateTransactionHandler>();
        services.AddScoped<DeleteTransactionHandler>();
        services.AddScoped<CreateBudgetHandler>();
        services.AddScoped<GetBudgetsHandler>();
        services.AddScoped<UpdateBudgetHandler>();
        services.AddScoped<DeleteBudgetHandler>();
        services.AddScoped<CreateSavingGoalHandler>();
        services.AddScoped<GetSavingGoalsHandler>();
        services.AddScoped<UpdateSavingGoalHandler>();
        services.AddScoped<DeleteSavingGoalHandler>();
        services.AddScoped<CreatePurchaseGoalHandler>();
        services.AddScoped<GetPurchaseGoalsHandler>();
        services.AddScoped<UpdatePurchaseGoalHandler>();
        services.AddScoped<DeletePurchaseGoalHandler>();
        services.AddScoped<CreateDebtHandler>();
        services.AddScoped<UpdateDebtHandler>();
        services.AddScoped<DeleteDebtHandler>();
        services.AddScoped<GetDebtsHandler>();
        services.AddScoped<AddSavingGoalContributionHandler>();
        services.AddScoped<UpdateSavingGoalContributionHandler>();
        services.AddScoped<DeleteSavingGoalContributionHandler>();
        services.AddScoped<GetSavingGoalContributionsHandler>();
        services.AddScoped<AddPurchaseGoalContributionHandler>();
        services.AddScoped<UpdatePurchaseGoalContributionHandler>();
        services.AddScoped<DeletePurchaseGoalContributionHandler>();
        services.AddScoped<GetPurchaseGoalContributionsHandler>();
        services.AddScoped<RegisterDebtPaymentHandler>();
        services.AddScoped<UpdateDebtPaymentHandler>();
        services.AddScoped<DeleteDebtPaymentHandler>();
        services.AddScoped<GetDebtPaymentsHandler>();
        services.AddScoped<CreateRecurringRuleHandler>();
        services.AddScoped<GetRecurringRulesHandler>();
        services.AddScoped<UpdateRecurringRuleHandler>();
        services.AddScoped<DeleteRecurringRuleHandler>();
        services.AddScoped<UpsertUserContextEntryHandler>();
        services.AddScoped<GetUserContextHandler>();
        services.AddScoped<DeleteUserContextEntryHandler>();
        services.AddScoped<GetFinanceOverviewHandler>();
        return services;
    }
}
